[tool.mypy]
disallow_untyped_defs = true
# Remove venv skip when integrated with pre-commit
exclude = ["build", "examples", "notebooks", "venv"]
ignore_missing_imports = true

[tool.ruff]
exclude = [
    ".venv",
    "__pycache__",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".ruff_cache",
    "examples",
    "notebooks",
    ".git"
]

[tool.codespell]
check-filenames = true
check-hidden = true
ignore-words-list = "ot"
# Remove .git and venv skips when integrated with pre-commit
# Feel free to un-skip docs, examples, and experimental, you will just need to
# work through many typos (--write-changes and --interactive will help)
skip = "./.git,./*venv,./docs,./examples,./experimental,*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt"
