[tool.codespell]
check-filenames = true
check-hidden = true
ignore-words-list = "ot"
# Remove .git and venv skips when integrated with pre-commit
# Feel free to un-skip docs, examples, and experimental, you will just need to
# work through many typos (--write-changes and --interactive will help)
skip = "./.git,./*venv,./docs,./examples,./experimental,*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt"

[tool.mypy]
disallow_untyped_defs = true
exclude = ["build", "examples", "notebooks"]
ignore_missing_imports = true

[tool.ruff]
exclude = [
    "examples",
    "notebooks",
]
ignore = [
    "COM812",
]
# Feel free to add more here
select = [
    "C408",
    "C411",
    "C414",
    "C416",
    "C419",
    "D202",
    "D209",
    "D213",
    "D403",
    "D405",
    "D416",
    "I",
    "PERF102",
    "PIE790",
    "PIE808",
    "PLR1711",
    "PT001",
    "PT003",
    "PT006",
    "PT023",
    "PT027",
    "RET501",
    "RET504",
    "RSE102",
    "RUF005",
    "RUF010",
    "RUF015",
    "RUF100",
    "SIM101",
    "SIM103",
    "SIM118",
    "SIM300",
    "TID252",
    "TRY201",
    "UP007",
    "UP008",
    "UP010",
    "UP015",
    "UP018",
    "UP028",
    "UP031",
    "UP032",
    "UP034",
    "UP037",
    "W291",
    "W292",
    "W293",
]
target-version = "py38"
unfixable = [
    "ERA001",
]

[tool.ruff.flake8-annotations]
mypy-init-return = true

[tool.ruff.pydocstyle]
convention = "google"

[tool.tomlsort]
all = true
in_place = true
spaces_before_inline_comment = 2  # Match Python PEP 8
spaces_indent_inline_array = 4  # Match Python PEP 8
trailing_comma_inline_array = true
