name: docs
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - sphinx>=4.3.0
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - nbsphinx
    - nbsphinx-link
    - myst-parser
    - docutils<0.17
    - furo>=2023.3.27
    - -e ../
